#!/usr/bin/env bash

# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=telegramd
PIDFILE=/home/pi/Projects/FinnnBot/$NAME.pid
#This is the command to be run, give the full pathname
DAEMON=/home/pi/Projects/FinnnBot/main_bot.py

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
        echo -n "Starting daemon: "$NAME
    	start-stop-daemon --start --background --make-pidfile $PIDFILE --pidfile $PIDFILE --exec $DAEMON
        echo "."
	;;
  stop)
        echo -n "Stopping daemon: "$NAME
        start-stop-daemon --stop --pidfile $PIDFILE
        echo "."
	;;
  restart)
        echo -n "Restarting daemon: "$NAME
    	# start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile $PIDFILE
        start-stop-daemon --stop --retry 30 --pidfile $PIDFILE
        start-stop-daemon --start --background --make-pidfile $PIDFILE --pidfile $PIDFILE --exec $DAEMON
    	echo "."
	;;

  *)
	echo "Usage: "$1" {start|stop|restart}"
	exit 1
esac

exit 0
